[package]
name = "parihsz/chrono"
description = "Custom character replication"
version = "0.3.0"

license = "MIT"
authors = ["Parihsz", "Azimus", "Tazmondo"]

realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["default.project.json", "src", "src/**", "LICENSE.txt"]